### ISSUE TITLE
anywidget not working with Panel + ipywidgets-bokeh: Class null not found in module @jupyter-widgets/base@2.0.0

### ISSUE THREAD

**Issue by MarcSkovMadsen** [manzt/anywidget#100]
Hi

I am a user of and contributor to [HoloViz Panel](https://panel.holoviz.org). One of the reasons I prefer Panel for my data apps is that it works with ipywidgets. I would like Panel and Anywidget to work together to enable users to easily develop powerful data apps using Anywidget and derived widgets like [mapwidget](https://github.com/giswqs/mapwidget).

Unfortunately it currently does not work.

I don't know which python package causes the issue. So I've cross posted here https://github.com/bokeh/ipywidgets_bokeh/issues/89.

## Reproducible Example

```bash
pip install panel==0.14.4 ipywidgets-bokeh==1.3.0 anywidget==0.2.0
```

**script.py**

```python
import anywidget
import traitlets

import panel as pn

pn.extension("ipywidgets")

class CounterWidget(anywidget.AnyWidget):
    _esm = """
    export function render(view) {
      let getCount = () => view.model.get("count");
      let button = document.createElement("button");
      button.classList.add("counter-button");
      button.innerHTML = `count is ${getCount()}`;
      button.addEventListener("click", () => {
        view.model.set("count", getCount() + 1);
        view.model.save_changes();
      });
      view.model.on("change:count", () => {
        button.innerHTML = `count is ${getCount()}`;
      });
      view.el.appendChild(button);
    }
    """
    _css="""
    .counter-button { background-color: #ea580c; }
    .counter-button:hover { background-color: #9a3412; }
    """
    count = traitlets.Int(0).tag(sync=True)

counter = CounterWidget()
pn.panel(counter).servable()
```

```bash
panel serve script.py
```

Open http://localhost:5006/script and see the exception in the browser console.

![image](https://user-images.githubusercontent.com/42288570/227778927-9e0dace3-0cab-4ff5-97a1-649c71bc85f0.png)

```bash
Class null not found in module @jupyter-widgets/base@2.0.0
```

Any help would be appreciated. Thanks.

**Comment by manzt** [comment]
Hmm, this is my first time seeing Panel, so I'm not quite sure what's going on. It's related to how anywidget's only front-end dependnecy is being loaded. We are on v6, so i'm not sure why 2.0 is being requested.

Could this be related to this? cc @maartenbreddels

https://github.com/jupyter-widgets/ipywidgets/blob/511663a56324cea5324f49a65ebe25e2f1b04d87/docs/source/changelog.md?plain=1#L316

**Comment by manzt** [comment]
Just cut a release, and unfortunately I don't think the fix in #107 resolved the issue. I'll take a closer look tomorrow or over the weekend.

**Comment by ndmlny-qs** [comment]
I have been studying this error, and I think I have hunted down where `@jupyter-widgets/base@2.0.0` is being (mis)called from; ipywidgets in `base-manager/manager-base.ts` in a method called `loadModelClass`.

https://github.com/jupyter-widgets/ipywidgets/blob/511663a56324cea5324f49a65ebe25e2f1b04d87/packages/base-manager/src/manager-base.ts#L785

```typescript
  protected async loadModelClass(
    className: string,
    moduleName: string,
    moduleVersion: string
  ): Promise<typeof WidgetModel> {
    try {
      const promise: Promise<typeof WidgetModel> = this.loadClass(
        className,
        moduleName,
        moduleVersion
      ) as Promise<typeof WidgetModel>;
      await promise;
      return promise;
    } catch (error) {
      console.error(error);
      const msg = `Failed to load model class '${className}' from module '${moduleName}'`;
      return widgets.createErrorWidgetModel(error, msg);
    }
  }
```

The `2.0.0` is being defined in ipywidgets at file `_version.py` here

https://github.com/jupyter-widgets/ipywidgets/blob/511663a56324cea5324f49a65ebe25e2f1b04d87/python/ipywidgets/ipywidgets/_version.py#L10

```python
# These are *protocol* versions for each package, *not* npm versions. To check, look at each package's src/version.ts file for the protocol version the package implements.
__jupyter_widgets_base_version__ = '2.0.0'
__jupyter_widgets_output_version__ = '1.0.0'
__jupyter_widgets_controls_version__ = '2.0.0'
```

You can have the latest version of `jupyter-widgets`, but it is here that is causing the issue. I've been having the hardest time getting a dev environment for ipywidgets to work, but I added a breakpoint in the dev console at `loadModelClass` within `ipywidgets_bokeh` (since it's packing ipywidgets code for itself). I then changed the `__jupyter_widgets_base_version__ = '2.0.0'` to `__jupyter_widgets_base_version__ = 'zort'` in my installed version of ipywidgets and got this out of the console

![image](https://user-images.githubusercontent.com/60523020/232646813-9276bf5b-a667-4f3a-bec0-8bf8fab558c8.png)

It would seem that the `moduleVersion` being read by `loadModelClass` is reading the "protocol" version defined in ipywidgets.

**Comment by ndmlny-qs** [comment]
I've created an issue here https://github.com/jupyter-widgets/ipywidgets/issues/3761 if @manzt or @MarcSkovMadsen would like to investigate further

**Comment by manzt** [comment]
Following https://github.com/bokeh/ipywidgets_bokeh/pull/97 for a fix (hopefully).

**Comment by manzt** [comment]
Seems to be fixed in `ipywidgets-bokeh==1.5.0`!

<img width="712" alt="image" src="https://github.com/manzt/anywidget/assets/24403730/73cbe089-d6bc-468d-a7cf-efde88847f63">

**Comment by manzt** [comment]
Thanks for the thorough investigation, @ndmlny-qs! 🙏

**Comment by saulshanabrook** [comment]
I have encountered the same error when using `embed_minimal_html`, see https://github.com/jupyter-widgets/ipywidgets/issues/3761#issuecomment-1755563436

For now, I will try using Panel as a workaround, since it seems like it was fixed there.

**Comment by MarcSkovMadsen** [comment]
Works for me. Panel now works with AnyWidget when I've tested. See https://discourse.holoviz.org/t/panel-works-with-anywidget/6466

https://github.com/manzt/anywidget/assets/42288570/297b45b8-7071-4c08-bdd4-a8a6540c8c0f

https://github.com/manzt/anywidget/assets/42288570/2167383d-97e5-4565-844b-3c10187e23d0

https://github.com/manzt/anywidget/assets/42288570/c8b64fe8-25a5-44c8-ba8e-eabbdd3132c7

https://github.com/manzt/anywidget/assets/42288570/2198812a-e33c-4307-b62d-f4bfd74a8ee5

**Comment by manzt** [comment]
great!
