### ISSUE TITLE
_esm as kwarg

### ISSUE THREAD

**Issue by maartenbreddels** [manzt/anywidget#115]
Now we need to inherit from AnyWidet and add the _esm. I've noticed many times in the notebook I want to pass a Path or str to the AnyWidget ctor. Does this make sense to add?

**Comment by manzt** [comment]
I'm not sure I understand the request. So right now, creating a widget requires subclassing, and the desired API would be to allow something more dynamic? You'd also need to add traits inline, I assume.

```python
widget = AnyWidget(_esm=Path("index.js"))
widget.add_traits(value=Int(0).tag(sync=True))
```

**Comment by maartenbreddels** [comment]
Indeed. And then my follow up question is: What about subclassing from ValueWidget ? https://github.com/jupyter-widgets/ipywidgets/blob/main/python/ipywidgets/ipywidgets/widgets/valuewidget.py#L10 ?

I've added the same trait in ipyreact, but I think inheriting from ValueWidget might be a good idea since that would also allow it to be used in the `interact` machinery.

**Comment by manzt** [comment]
Finally had the chance to look into this today. I'm afraid that trying to add this functionality will increase the complexity of handling the setup for `_esm`, which is already quite complicated! There is a bit of friction to try to get the `traitlets.HasTraits` metaclass to play nicely with our path-based API. Additionally, a benefit of the class-based API ensures that only one file watcher thread is spawned per class during development (we use `__init_subclass_`).

For now, I think the workaround is pretty minimal:

```python
def dynamic_widget(_esm: pathlib.Path, **traits: traitlets.TraitType):
    class Widget(anywidget.AnyWidget):
        _esm = _esm
    widget = Widget()
    widget.add_traits(**traits)
    return widget
```

Also, since `_esm` is a trait, you can assign `_esm` before rendering (although in this case you don't get anywidget's HMR during development).

```python
widget = AnyWidget()
widget._esm = "export function render(view) { console.log(view.model.get('value')) }"
widget.add_traits(value=Int(0).tag(sync=True))
```

Happy to be convinced otherwise!

> What about subclassing from `ValueWidget `? 

This is also interesting! I see how this ties to wanting `_esm` in the ctor, but again I'm not quite sure how this could be handled nicely with anywidget's HMR and file detection.

**Comment by manzt** [comment]
Going to close for now.
