### ISSUE TITLE
Lifecycle methods or non-view methods

### ISSUE THREAD

**Issue by maartenbreddels** [manzt/anywidget#266]
Hi,

right now, only a render method can be defined, which will be triggered when a view is created. It may also be useful to perform operations when a widget gets created (not a view), and when a widget gets destroyed. This allows for widgets similar to the one powering jslink etc.
Original questions that triggered this:
https://github.com/widgetti/ipyreact/issues/44
cc @giswqs

**Comment by giswqs** [comment]
@maartenbreddels Thank you for looking into this. There are so many JavaScript plugins available for leaflet. It would be a game-changer if we can make those plugins work with ipyleaflet through anywidget/ipyreact.

**Comment by manzt** [comment]
Thanks for opening the issue. This is something that I've been thinking about for some time and a use case I want to support, but I haven't settled on an API because I want to make sure we can handle other use cases. Thanks for sharing the one from @giswqs!

One thing that I'd been considering is something like `setup` (name TBD):

```js
export function setup() {
   // runs when model is created
   return {
     data: "...",
     foo: 100,
   };
}

export function render({ model, el }, context) {
  let { data, foo } = context;
}
```

A pattern I've observed in Jupyter Widgets is that there is some "data" that often gets appended to the `DOMWidgetModel` on initialization, and then views expect/mutate this data (but not with the on/off methods). So I've been considering an API where a `setup` function can do some initialization logic, but then also create some data that can be referenced mutated by other views.

I'm a bit nervous about passing around data this way and introducing a confusing mental model. So, perhaps to start we can think about just introducing a "setup" hook and later decide if it can return any state to pass around to views.
