### ISSUE TITLE
`(core dumped) poetry run pytest` on CI when `_should_start_thread` is `True`

### ISSUE THREAD

**Issue by kylebarron** [manzt/anywidget#374]
I'm updating anywidget to version 0.7.1 to take advantage of the really nice https://github.com/manzt/anywidget/pull/345. One consequence is that I can't run CI tests without the JS parts built, because if those files aren't found, anywidget will error.

I've been hitting a very consistent `(core dumped) poetry run pytest` on Github Actions CI when the JS files exist and when `watchfiles` is installed. It looks to be some sort of threading issue, and so not having `watchfiles` installed ensures that `_should_start_thread` is `False`:
https://github.com/manzt/anywidget/blob/2600bd8a85c7e8e5f5ce572410592314b713ec72/anywidget/_util.py#L178-L187

Here's a minimal example of what I'm seeing: https://github.com/developmentseed/lonboard/pull/234

```
Run poetry run pytest
============================= test session starts ==============================
platform linux -- Python 3.8.18, pytest-7.4.3, pluggy-1.3.0
rootdir: /home/runner/work/lonboard/lonboard
plugins: anyio-4.0.0
collected 11 items

tests/test_layer.py ..                                                   [ [18](https://github.com/developmentseed/lonboard/actions/runs/6827322556/job/18569190597#step:13:19)%]
tests/test_map.py .                                                      [ 27%]
tests/test_traits.py ........                                            [100%]

============================== 11 passed in 3.66s ==============================
FATAL: exception not rethrown
/home/runner/work/_temp/4f63a42f-5562-4a63-a9ca-331e37c02752.sh: line 1:  [22](https://github.com/developmentseed/lonboard/actions/runs/6827322556/job/18569190597#step:13:23)85 Aborted                 (core dumped) poetry run pytest
```

This is using anywidget `0.7.1` and watchfiles `0.21.0`

**Comment by manzt** [comment]
maybe we could create a environment variable? to force no HMR?

**Comment by kylebarron** [comment]
Yeah, that would be an ok solution... As a workaround I make sure I don't install `watchfiles` on CI. It would be _nice_ if we could figure out what's actually wrong, but that might be a 🕳️

**Comment by manzt** [comment]
Hmm, ok looking into this. The root of the issue is that we automatically read the file if a path is detected in class definition. Maybe we should delay this until the first instance of the class is created.

**Comment by kylebarron** [comment]
I don't think that's the root issue here. Maybe that was before I built the JS resources on CI, but now that the JS files exist, the class initialization works fine. It's something specifically with the threading around the HMR.

**Comment by manzt** [comment]
Oh ya, threads and CI can be really tricky.

**Comment by tlambert03** [comment]
haven't looked too closely yet, but if the issue only happens when `start_thread` is True and `FileContents._background_thread` is started, then the the first thing I'd try to do (just to confirm that we're right about the issue) is to force that thread to be stopped and joined in any test where it's used.  That might make for some temporarily ugly test code, but if you can demonstrate that joining/stopping that thread always prevents the core dump, then you can look into test fixtures that make sure that any FileContents threads that get started up in a test are definitely stopped.

**Comment by manzt** [comment]
dfdsfjjjjdfasdf
asdfdf

**Comment by crazycapivara** [comment]
I got the same problem in [py-maplibre](https://github.com/eodaGmbH/py-maplibregl), where using the widget is optional. Beside the error with pytest, I also get an error when I import the widget in `__init__.py` but it is not used, because e. g. the user only uses the Shiny integration of maplibre. When the Shiny app is stopped, the `core dumped` is thrown.

**Comment by manzt** [comment]
Thanks for pinging this again. I have made https://github.com/manzt/anywidget-core-dump-repro to try to reproduce the error and get to the bottom of it, as @tlambert03 described.

**Comment by manzt** [comment]
I just added a join/stop at the end of the code, and the thread never joined (I ended up cancelling the test in GH Actions): https://github.com/manzt/anywidget-core-dump-repro/actions/runs/7616199837

**Comment by manzt** [comment]
Next release of anywidget will make starting the background thread _opt-in_ with an environment variable`ANYWIDGET_HMR=1`.
