### ISSUE TITLE
Enable rendering of images on GitHub and after kernel restart

### ISSUE THREAD

**Issue by kolibril13** [manzt/anywidget#396]
I just wrote a small [ImageWidget](https://github.com/kolibril13/anywidget-image/blob/main/js/widget.jsx) with anywidget and React.

Now, it would be amazing if it was possible to render that image on GitHub, and even after kernel restart! ✨ 

That is possible with `from IPython.display import Image` See [notebook1](https://github.com/kolibril13/anywidget-image/blob/main/image_ipython.ipynb).
But that does not work when I use `from ipywidgets import Image` See [notebook2](https://github.com/kolibril13/anywidget-image/blob/main/image_ipywidgets.ipynb)
Likewise, it does not work with anywidget. See [notebook3](https://github.com/kolibril13/anywidget-image/blob/main/image_anywidget.ipynb)
Here's an overview summary how it currently looks like:

<img width="868" alt="image" src="https://github.com/manzt/anywidget/assets/44469195/8e0290db-112a-41d2-9a42-b2cbfe025d3d">

Related issues:

https://github.com/jupyterlab/jupyterlab/issues/15361

https://github.com/jupyter-widgets/ipywidgets/issues/2280

**Comment by manzt** [comment]
> But that does not work when I use from `ipywidgets import Image`

Yes, this is expected behavior for widgets. It seems you've found and linked the related issues, so I don't really know what to say other than to explain why this is happening.

When a Python object is the last element in a notebook cell, the ipython kernel looks for a `_repr_mimbundle_` method and invokes that returns a dictionary keyed [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types). 

You can inspect the mimebundles by calling the `_repr_mimebundle_()` yourself:

```python
import IPython.display

IPython.display.Image("./dog.jpg")._repr_mimebundle_()
# ({'image/jpeg': '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopG
```

```python
import ipywidgets

with open("./dog.jpg", "rb") as f:
    data = f.read()
    
ipywidgets.Image(value=data)._repr_mimebundle_()
# {
#  'text/plain': "Image(value=b'\\xff\\xd8\\xff\\xe0\\x00\\x10JFIF\\x00\\x01\\x01\\x00\\x00\\x01\\x00\\x01\\x00\\x00\\xff\\xdb\\x00C\\x00\\x06\\x04\\x0…",
#  'application/vnd.jupyter.widget-view+json': {
#    'version_major': 2,
#    'version_minor': 0,
#    'model_id': '57bf31944747439a96a70e368d2ef891'
#   }
# }
```

This dictionary gets saved to the notebook (JSON) and then is interpreted later by whatever environment is rendering the JSON notebook.

As you can see, for the `IPython.display` the image data is embedded as a base64-encoded string, whereas the widget has a plain text repr as well as a custom `application/vnd.jupyter.widget-view+json` MIME type describing the widget. Rendering this MIME type requires executing JavaScript, so many static renderers (like GitHub) fallback to using the plain text repr. I don't anticipate that there will ever be support for executing JavaScript because it would be a security concern for GitHub.

It might be possible to mutate the notebook cell and save the `image/jpeg` data, but this is not what Widgets were designed for.

**Comment by kolibril13** [comment]
Thank you so much for these insights, I really appreciate your time and effort.

I agree, modifying the notebook does not sound like best practice.

Your last example that overwrites the  _repr_mimbundle_ with  `mimebundle["image/jpeg"] = ... ` works great and renders great on GitHub as well -> [notebook4](https://github.com/kolibril13/anywidget-image/blob/main/image_mime_type.ipynb)

I've extended your example by ` metadata = {"image/jpeg": {"width": self.width}}`, so that the width is also stored in the notebook metadata, here's the updated example:
```py
import ipywidgets
import base64

class MyImageWidget(ipywidgets.Image):
    def _repr_mimebundle_(self, *args, **kwargs):
        mimebundle = super()._repr_mimebundle_(*args, **kwargs)
        encoded_image = base64.encodebytes(self.value).decode("utf-8")
        mimebundle["image/jpeg"] = encoded_image
        metadata = {"image/jpeg": {"width": self.width}}
        return mimebundle, metadata

with open("./cute_dog.jpg", "rb") as f:
    data = f.read()

img = MyImageWidget(value=data, width="300px")
img
```

Next, I want to explore how to embed an image into a notebook after some interactions in the widget happened.
I think this is a use case that a lot of notebook users might encounter, and therefore it would be great to have a button that converts a widget into an image of image/jpeg type. 

I've just written a prototype here: https://github.com/kolibril13/anywidget-image/blob/main/js/widget_convert.jsx#L5-L19
which adds a convert button
<img width="449" alt="image" src="https://github.com/manzt/anywidget/assets/44469195/03d77e02-aab8-4209-82cc-3ee8ff1d7d1a">

The button does not yet have an effect. 
Do you have a suggestion, how the mimetype conversion could happen here?
I've introduced the traitlet `embed_image` that changes to True when the button is pressed.
From the python side,  it could look like this

```py
    embed_image = Bool(False).tag(sync=True)

    @observe("embed_image")
    def _observe_embed_image(self, change):
        print("Converted the image to image/jpeg mime type")
        # now some conversion code here.
```

but is there maybe a way to make this conversion directly from the JavaScript/React side?
