### ISSUE TITLE
Import a local js file into anywidget _esm fails

### ISSUE THREAD

**Issue by mlamoureux** [manzt/anywidget#399]
I'm trying to import a function from a local file. My _esm code in the anywidget starts as:
```
    _esm = """
    import  { draw } from './square.js';
    export function render({ model, el }) {
    ...
```
I get the error message: 
```
Failed to create view for 'AnyView' from module 'anywidget' with model 'AnyModel' from module 'anywidget'
TypeError: Failed to resolve module specifier "./square.js". Invalid relative url or base scheme isn't hierarchical.
```  
 I'm able to import functions from https:// addresses. Is there some trick to import from my own local files?

**Comment by mlamoureux** [comment]
![image](https://github.com/manzt/anywidget/assets/13968887/8d9241c4-dc53-4296-a66c-4c8f4066a122)

**Comment by mlamoureux** [comment]
That's a snapshot of the numerical simulation wave motion, running in an "anywidget." It shows a wave packet refracting across an interface, to demonstrate Snell's law. The point of the widgets is to add some buttons and sliders to control various parameters in the simulations, to make it easy to use.

**Comment by manzt** [comment]
Wow, very nice! Thanks for sharing.

> It's unfortunate, though, as I am doing some numerical simulations with the GPU and it is convenient to have the code broken up into modules (some for the math, some for the GPU, some for the graphical rendering), which makes it easier to maintain.

Understood, and I totally agree. This is something I've been wanting for anywidget since the beginning to let us fully embrace ESM, but without introducing some extra front-end build tooling to anywidget's ore, I don't see a way to support it. 

Like I mentioned, you could always configure a tool like `esbuild` to create the single 1000+ line file for you from your source files:

```js
// lib/square.js
export function draw() { /* ... */ }

// lib/main.js
import { draw } from "./square.js";
export function render({ model, el }) {
  /* ... */
}
```

```
npx esbuild bundle --format=esm --outfile=bundle.js lib/main.js # --watch if you want to compile on demand
```

```python
import pathlib
import anywidget

class Widget(anywidget.AnyWidget):
    _esm = pathlib.Path(__file__).parent / "bundle.js"
```

Although, I'd only pursue this option if the benefits of better code organization outweighs no build tooling. Esbuild is an excellent and very minimal tool, but I very much prefer avoiding these things if possible.

> I'm really happy, though, to have "anywidgets" available as it lets me do a lot of interesting coding that takes advantage of the local machine (GPUs, USB devices, etc) through JS and it runs on both the classic notebooks and Jupyter Lab.

That's great to hear.
