### ISSUE TITLE
Types: some backbone.js methods are missing in AnyModel's interface

### ISSUE THREAD

**Issue by benbovy** [manzt/anywidget#402]
The following backone.js methods for registering callbacks are missing in the `AnyModel` interface: `listenTo`, `stopListening`, `once` and `listenToOnce`.

Especially with #395 (more control on widget lifecyle), those methods may be useful for some use cases. See for example https://github.com/jupyter-widgets/ipywidgets/pull/69. In my case I'd also like to execute some cleanup logic on model destroy, which works fine with `model.on('destroy', callback)` but it would be cleaner with `model.once('destroy', callback)`.

**Comment by manzt** [comment]
Hi, thanks for bringing this up. The decision to exclude `listenTo`, `stopListening`, `once`, and `listenToOnce` from the AnyModel interface was [intentional](https://github.com/manzt/anywidget/pull/138). The aim is to streamline the AnyWidget's API and reduce its reliance on ipywidgets and Backbone.js.

However, I understand your need for these methods, especially for cases like executing cleanup logic on model destruction. 

You can implement some of these methods in user-land. Here’s a basic example for the `once` method:

```js
function once(model, event, callback) {
  const handler = (...args) => {
    model.off(event, handler);
    callback.apply(model, args);
  };
  model.on(event, handler);
}
```

A goal of anywidget is to get rid of the dependency on backbone models and views API. The view is implicitly defined by the `render` function, and can define its own cleanup logic by returning a function:

```js
export function render({ model, el }) {
   // setup your view
   return () => {
    // teardown logic here
  };
}
```

The same applies for `initialize` once #395 lands.


```js
export default function() {
  return {
     initialize({ model }) {
      return () => { /* model cleanup */ }
     },
     render({ model, el }) {
       return () => { /* view cleanup */ }
     }
  }
}
```

In each of these functions, anywidget provides the third argument to `model.on`/`model.off`, context. Which means you can unsubscribe specifically to any events added within that context. For example:

```js
export function render({ model, el }) {
  const handler = () => console.log("foo");
  model.on("msg:custom", handler);
  let button = document.createElement("button");
  button.innerText = "remove event listener";
  button.addEventListener("click", () => {
    model.off("msg:custom", handler); // only unsubscribes the handler added above (but not other views)
  })
}
```
