### ISSUE TITLE
Feature request: is there a complete(ish) list of anywidgets that have been developed?

### ISSUE THREAD

**Issue by Coderambling** [manzt/anywidget#469]
Hi @manzt . Just had a look at anywidgets. Could not find a list / gallery of anywidgets on the website or elsewhere. Saw a couple on https://discourse.panel.org . Is there a list or gallery somewhere? Nice that it integrates with Panel btw!

**Comment by manzt** [comment]
Hi there! I'd love to add a section to the documentation. Some recent highlights from the community in our latest blog post: https://anywidget.dev/blog/a-year-with-anywidget/#community-highlights-and-updates

Also there are many examples shared on our [Discord](https://discord.gg/W5h4vPMbDQ).

**Comment by Coderambling** [comment]
Hey! Yes would be useful. I am working on the docs for Panel, and floated a suggestion to include a page that lists various resources for external widgets that can work with Panel. That's why I was looking for an anywidget gallery.

I think it would be good for anywidgets to have a gallery showing what's available so far. Most other frameworks / similar initiatives have something like this.

Do you have any feel for what the current "uptake" of anywidgets is?

**Comment by manzt** [comment]
Completely agree, just a matter of priorities and time. For context, I'm a PhD student and work on this in my spare time to support my work and others. I'd like to put more time into community and growing the project, but my priorities at the moment are stabilizing important features.

anywidget is relatively new compared to "most other frameworks," and there isn't a dedicated team supporting it's maintenance. We have [an active community](https://discord.gg/W5h4vPMbDQ) that is growing and I have started making some [video tutorials](https://www.youtube.com/channel/UCKg0ViId3WQh38w9GDwbbSQ) to teach anywidget.

I will work on a gallery, but this will require effort because I want it to be easy to contribute examples.

**Comment by Coderambling** [comment]
Nice! What is the Discord channel URL?

**Comment by Coderambling** [comment]
Totally get it! Great work, and make sense to focus on stabilising for now. Keep up the good work!

**Comment by Coderambling** [comment]
Totally get it! Great work, and makes sense to focus on stabilising for now. Keep up the good work!

Hope that people will still be encouraged to share their anywidgets in other ways, if not via pypi. Important for the ecosystem, and would save a lot of duplication of effort.

**Comment by manzt** [comment]
Well... I have to admit you got me with this one :) I'll announce tomorrow, but checkout the [community gallery](https://anywidget.dev/en/community/). Thanks for encouraging me to do it.
