### ISSUE TITLE
Can decorator @anywidget.experimental.command be used on ASYNC method?

### ISSUE THREAD

**Issue by MRYingLEE** [manzt/anywidget#654]
### Issue

So far, all the examples using the decorator of @anywidget.experimental.command use synchronous methods only.

I tried slightly changed official demo with asynchronous method:
```python
%pip install anywidget
import anywidget
import traitlets

class CounterWidget(anywidget.AnyWidget):
    _esm = """
    export default {
      async render({ model, el, experimental }) {
        let button = document.createElement("button");
        button.innerHTML = `count is ${model.get("value")}`;
        button.addEventListener("click", async () => {
          let [msg, buffers] = await experimental.invoke("_calculate", model.get("value"));
          button.innerHTML = `Result is ${msg}`;
          model.set("value", msg);
        });
        el.appendChild(button);
      },
    };
    """
    _css = """
    .counter-button {
      background-image: linear-gradient(to right, #a1c4fd, #c2e9fb);
      border: 0;
      border-radius: 10px;
      padding: 10px 50px;
      color: white;
    }
    """
    value = traitlets.Int(0).tag(sync=True)

    @anywidget.experimental.command
    async def _calculate(self, value, buffers):
        print("Start fetching data...")
        # Simulating a network delay with asyncio.sleep
        await asyncio.sleep(2)
        print("Data fetched from server!")
        return value + 1, buffers
    

w=CounterWidget(value=22)
w
```
and I met the issue of "Uncaught (in promise) TimeoutError: signal timed out".

I am wondering whether the decorator can be used on ASYNC method. 
Please clarify. 
Thanks,

### Recommended improvement

If yes, please provide an example with related document.
If not yet but possible, please add such a kind of feature in future.
If not possible, please mention the limit.

**Comment by manzt** [comment]
This is an experimental API, so there isn't official documentation available at this time. The `@anywidget.experimental.command` decorator does not currently support asynchronous commands. The limitation stems from the fact that these callbacks are executed by Jupyter, which has its own asynchronous event loop, introducing significant challenges when trying to integrate async methods.

It's worth noting that the `command` decorator is essentially syntactic sugar to tie together existing APIs that anywidget exposes to you as a widget developer. It goal to simplify the most common use cases and reduce boilerplate code. For scenarios requiring concurrent API calls, the command decorator may not be sufficient due to the complexity involved in handling async or threaded operations within the Jupyter environment (which are difficult to generalize).

If you need to implement concurrent API calls, I recommend looking into the implementation of `command` itself. This can be done without us making the simple `command` implementation more complicated.
